### ISSUE TITLE
Create constants for Relationship names

### ISSUE THREAD

**Issue by LycraLout** [rappen/LateboundConstantsGenerator#16]
Suggestion: Include Relationship names in the generated constants.

```
Relationship relationship = new Relationship(CrmConstants.account.account_primary_contact);
_service.Associate(Contact.EntityName, contactId, relationship, relatedAccountReferences);
```

This improvement would remove the need to "magic string" the relationship name when instantiating Relationships to be used in Associate calls.

**Comment by daryllabar** [comment]
The EarlyBoundGenerator already does this.

**Comment by daryllabar** [comment]
@LycraLout np.  I'm just giving Jonas a hard time.  Would love to know why you've chosen the delegateas solution.  If they're solution is better, and I should stop maintaining mine and point people to theirs, then I'm all for that! ;)

**Comment by LycraLout** [comment]
@daryllabar The compelling features of the delegateas solution are the strongly typed OptionSet values and the ability to deprecate fields. Other features like the Entity helper methods and easy config are nice but the two above are key for us.

**Comment by daryllabar** [comment]
The EBG has strongly typed optionsets, but what is meant by deprecating fields?  Is that the ability to generate properties with an obsolete attribute?

**Comment by LycraLout** [comment]
That's right. Set a configurable prefix string on the field display name and the generated classes will mark those properties as obsolete. We use [REDUNDANT] as the identifier. We're running an upgrade / redesign project of an existing system and this helps prevent us targeting legacy fields in our code.

**Comment by daryllabar** [comment]
Thanks @lycraLout for responding.  Probably won't add that feature, since it sounds like it should just be deleted, but that is an interesting idea...

**Comment by rappen** [comment]
FYI @LycraLout this feature has now been released along with a few other features.
https://twitter.com/rappen/status/1046659428332785664

Feel free to reach out with any comments!

**Comment by LycraLout** [comment]
Great stuff. Thanks. I'll update.
