### ISSUE TITLE
CLI Support

### ISSUE THREAD

**Issue by glosrob** [rappen/LateboundConstantsGenerator#27]
Can we run this from the command line and if not, would you accept a PR along these lines?

Something like a console app or powershell script that can be run via a build process or directly from Visual Studio.

This would need to:
- accept configuration values, perhaps from a config.json
- consume config and output file(s) using `CSharpUtils.GenerateClasses` to ensure output is consistent with the GUI

**Comment by rappen** [comment]
Hi Robert,

It is currently not possible, but I would absolutely appreciate a PR!

Jonas

**Comment by maerger** [comment]
Created some code and a PR - its not perfect yet but does the job...

**Comment by rappen** [comment]
Huge thanks!
