### ISSUE TITLE
owninguser Attribute

### ISSUE THREAD

**Issue by maerger** [rappen/LateboundConstantsGenerator#33]
Maybe I missed this feature: Is there a way to generate a constant for the "pseudo" Attribute owninguser?

**Comment by rappen** [comment]
Now there is! 😊
Or at least will be after next release.

![LCG Logical Attributes](https://user-images.githubusercontent.com/2572253/59800971-302f8780-92e8-11e9-9a9d-9de2b7c38c33.gif)

**Comment by rappen** [comment]
This fix is now published!
