### ISSUE TITLE
"Unable to evaluate query" error when loading entities on a CRM 2011 instance

### ISSUE THREAD

**Issue by Jamizzle93** [rappen/LateboundConstantsGenerator#36]
Hello,

This plugin works absolutely perfectly with our CRM 2016 instances.
However, when I attempt to load the entities when connected to our of our CRM 2011 instances I receive an error which simply reads "Unable to evaluate query"?

Is there a potential fix for this?

I'm happy to provide some more information if it is needed.

Thanks!

**Comment by rappen** [comment]
2011! I'm getting all sentimental here...
It is most likely a metadata attribute or two that the tool is querying that were not available back in the days...
If you have any more info I can look into it!

**Comment by Jamizzle93** [comment]
@rappen - Many thanks for your quick reply!

Not too sure what information I can provide. Is there anything, in particular, that would help you with diagnosing the issue?

Here's a little snippet from the error log.

> Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	23/09/2019 14:26:17  .[TerminalFailure] Failed to Execute Command - RetrieveMetadataChanges : RequestID=de5d333a-7188-4fbe-b883-1b115e967d87 : Execute (RetrieveMetadataChanges) request to CRM from IOrganizationService duration=00:00:00.3850070 ExceptionMessage = Unable to evaluate query
Source	: mscorlib
Method	: HandleReturnMessage
Date	: 23/09/2019
Time	: 14:26:17
Error	: Message: Unable to evaluate query
ErrorCode: -2147204733
Trace: 
Stack Trace	: Server stack trace: 
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

>Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Xrm.Sdk.IOrganizationService.Execute(OrganizationRequest request)
   at Microsoft.Xrm.Sdk.Client.OrganizationServiceProxy.ExecuteCore(OrganizationRequest request)
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.CrmCommand_Execute(OrganizationRequest req, String errorStringCheck)
======================================================================================================================
Inner Exception Level 1	: 
==OrganizationServiceFault Info=======================================================================================
Error	: Message: Unable to evaluate query
ErrorCode: -2147204733
Trace: 
Time	: 23/09/2019 13:26:16
ErrorCode	: -2147204733
Date	: 23/09/2019
Time	: 14:26:17
Trace	: Not Provided
======================================================================================================================
Inner Exception Level 2	: 
==OrganizationServiceFault Info=======================================================================================
Error	: Message: The type EntityMetadata does not have a property named EntityColor
ErrorCode: -2147204733
Trace: 
Time	: 23/09/2019 13:26:16
ErrorCode	: -2147204733
Date	: 23/09/2019
Time	: 14:26:17
Trace	: Not Provided
======================================================================================================================

**Comment by rappen** [comment]
Looks like since the `RetrieveMetadataChanges` request was not available back in 2011 this tool will not work with that version without quite extensive work...
If you have the time and knowledge to create a pull request for it I am open for that, but unfortunately I won't.
Trying my best, feel free to share ☺ https://twitter.com/rappen/status/1196458352685002753

**Comment by rappen** [comment]
@Jamizzle93 which update of 2011 are you using?
Re: https://twitter.com/XrmToolBox/status/1196507717319503872

**Comment by Jamizzle93** [comment]
> @Jamizzle93 which update of 2011 are you using?
> Re: https://twitter.com/XrmToolBox/status/1196507717319503872

Thanks for looking into this @rappen 

I've seen the tweet, our CRM 2011 instance is running version 5.0.9690.4150. I'm not sure how much help this is.
![Dynamics2011Version](https://user-images.githubusercontent.com/5894967/69156757-d243dd80-0adb-11ea-87eb-5b2cddc0d083.PNG)


Our supplier is unfortunately in charge of updates, so it may not be easy for us to update the system. We are however currently working with both our suppliers and our customers to move them onto CRM 2016, so I'm happy to close this issue if it will not be a quick fix.

Thanks for all the time you've spent on it so far though, it is much appreciated. 👍

**Comment by rappen** [comment]
That would correspond to UR 17, so according to @mscrmtools it should work...
https://buildnumbers.wordpress.com/crm/
I guess I will simply close this issue then with "unknown error, hard to solve" 😉
