### ISSUE TITLE
Load Project doesn't load the Solution selected when the project was saved

### ISSUE THREAD

**Issue by ramblingreece** [rappen/LateboundConstantsGenerator#45]
As in the subject.

Reproducible Steps:

1. Change settings and select a solution
2. Save project
3. Change settings again and select a different solution
4. Load the saved project

The result is the last solution selected is the one that remains selected.

**Comment by rappen** [comment]
As designed.
Selecting a solution is a filtering mechanism to easier find your entities, the project settings save and load which entities (etc) that has been selected for the project.

Feel free to reopen if you don't like the explanation ☺
